export const AUTH_ERROR_CODE = {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
    INVALID_SESSION: 'INVALID_SESSION',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',
    PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
    INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
    RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
    RESET_TOKEN_USED: 'RESET_TOKEN_USED',
} as const;
